
services:
    mongo:
        image: mongo:latest
        container_name: card_sorter_mongodbdev
        
        ports:
            - "27017:27017"
        environment:
          MONGO_INITDB_ROOT_USERNAME: "rest_api"
          MONGO_INITDB_ROOT_PASSWORD: "password"
          MONGO_INITDB_DATABASE: "card_sorter"
          
        volumes:
            - ./mongodata:/data/db

    mongo-express:
      image: mongo-express:latest
      
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: "rest_api"
        ME_CONFIG_MONGODB_ADMINPASSWORD: "password"
        ME_CONFIG_MONGODB_SERVER: "mongo"
        ME_CONFIG_BASICAUTH_USERNAME: rest_api
        ME_CONFIG_BASICAUTH_PASSWORD: password
        #ME_CONFIG_MONGODB_URL: "card_sorter_mongodbdev://card_sorter_mongodbdev:27017"
      depends_on:
        - mongo
