INSERT INTO USER_TABLE(ID, USERNAME, PASS, EMAIL) VALUES (1, 'user1', 'pass1', 'email@email.com');

INSERT INTO STUDY(ID, USER_ID, DESCRIPTION, TITLE, COMPLETED_NO, ABANDONED_NO, EDIT_DATE, LAUNCHED_DATE, END_DATE, IS_LIVE, MESSAGE_TEXT) VALUES (2, 1, 'A study description', 'A study about something', 1, 10, '2018-10-12', '1999-01-08', NULL, TRUE, 'DEAR PARTICIPANT I THANK YOU A LOT FOR COMPLETING THIS STUDY. I WILL ALWAYS BE THERE TO EXPRESS MY GRATITUDE TO YOU AND YOUR FAMILY. TAKE CARE OF YOURSELF.');

INSERT INTO STATS(STUDY_ID, AVERAGE_SORT, COMPLETION, CLUSTERS_CALCULATING, CLUSTERS_CHANGED, CLUSTERS, SIMILARITY_MATRIX) VALUES (2, 10.0, 100, FALSE, FALSE, '{}', '{"matrix": [], "cardNames": ["a card yo"], "cardId": [11]}');

INSERT INTO PARTICIPANT(ID, STUDY_ID, CARDS_SORTED, TIME_SPAN, CATEGORIES_NO, NOT_SORTED, COMMENTS, CATEGORIES) VALUES (21, 2, 1, 10, 1, 0, 'EVERYTHING WAS OKAY MATE. TAKE CARE. NICHE STUDY IMO.', ARRAY['{"name": "a category yo", "cardNames": ["a card yo"]}'::json]);

INSERT INTO CARDS(ID, STUDY_ID, CARD_NAME, DESCRIPTION) VALUES (11, 2, 'a card yo', 'm8 this is a card.');

INSERT INTO CATEGORIES(ID, STUDY_ID, CATEGORY_NAME) VALUES (31, 2, 'a category yo');

INSERT INTO CARDS_CATEGORIES(CARD_ID, CATEGORY_ID, FREQUENCY) VALUES (11, 31, 1);