INSERT INTO USER_TABLE(USERNAME, PASS, EMAIL) VALUES ('user1', '$6$rounds=656000$H4CW.ZEPqaGbYhcp$ZnTASvYBu.dqKQjjgZpt0HiyoCNTYGpZeOyuz9uECjE3HA6SU0j3a7MAyfQgeoZK9.9kSwFa7HPYsZvxhTHJp/', 'email@email.com');

INSERT INTO STUDY(USER_ID, DESCRIPTION, TITLE, COMPLETED_NO, ABANDONED_NO, EDIT_DATE, LAUNCHED_DATE, END_DATE, IS_LIVE, MESSAGE_TEXT) VALUES (1, 'A study description', 'A study about something', 1, 10, '2018-10-12', '1999-01-08', NULL, TRUE, 'DEAR PARTICIPANT I THANK YOU A LOT FOR COMPLETING THIS STUDY. I WILL ALWAYS BE THERE TO EXPRESS MY GRATITUDE TO YOU AND YOUR FAMILY. TAKE CARE OF YOURSELF.');

INSERT INTO STATS(STUDY_ID, AVERAGE_SORT, COMPLETION, CLUSTERS_CALCULATING, CLUSTERS_CHANGED, CLUSTERS, SIMILARITY_MATRIX) VALUES (1, 10.0, 100, FALSE, FALSE, '{}', '{"matrix": [], "cardNames": ["a card yo"], "cardId": [1]}');

INSERT INTO PARTICIPANT(STUDY_ID, CARDS_SORTED, TIME_SPAN, CATEGORIES_NO, NOT_SORTED, COMMENTS, CATEGORIES) VALUES (1, 1, 10, 1, 0, 'EVERYTHING WAS OKAY MATE. TAKE CARE. NICHE STUDY IMO.', ARRAY['{"name": "a category yo", "cardNames": ["a card yo"]}'::json]);

INSERT INTO CARDS(STUDY_ID, CARD_NAME, DESCRIPTION) VALUES (1, 'a card yo', 'm8 this is a card.');

INSERT INTO CATEGORIES(STUDY_ID, CATEGORY_NAME) VALUES (1, 'a category yo', 1);

INSERT INTO CARDS_CATEGORIES(CARD_ID, CATEGORY_ID, FREQUENCY) VALUES (1, 1, 1);